name: luftdaten.at
description: Luftdaten.at - Air Quality Measurement
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.7.0+66

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  permission_handler: ^12.0.0
  flutter_reactive_ble: ^5.2.0
  another_flushbar: ^1.12.30
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  json_annotation: ^4.8.1
  syncfusion_flutter_charts: ^29.1.37+1
  flutter_background_service: ^5.0.1
  flutter_local_notifications: ^19.0.0
  flutter_native_splash: ^2.3.2
  flutter_map_location_marker: ^9.1.1
  flutter_compass: ^0.8.0
  path_provider: ^2.1.1
  share_plus: ^10.0.2
  package_info_plus: ^8.0.0

  #bluetooth_enable_fork: ^0.1.6
  bluetooth_enable:
    #path: '../bluetooth_enable'
    git:
      url: https://github.com/n11ik/bluetooth_enable.git

  app_settings: ^7.0.0
  intl: ^0.20.2
  latlong2: ^0.9.0
  google_fonts: ^6.3.0
  wakelock_plus: ^1.1.3
  get_storage: ^2.1.1
  url_launcher: ^6.1.14
  flutter_spinkit: ^5.2.0
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  two_dimensional_scrollables: ^0.3.0
  flutter_svg: ^2.0.8
  i18n_extension: ^15.0.4
  device_info_plus: ^11.3.0
  camera: ^0.11.0
  flutter_displaymode: ^0.6.0
  screenshot: ^3.0.0
  flutter_file_dialog: ^3.0.2
  vibration: ^3.1.3
  get_it: ^8.0.0
  logger: ^2.0.2+1
  http: ^1.1.0
  network_info_plus: ^6.0.1
  syncfusion_flutter_datepicker: ^29.1.37
  file_picker: ^10.3.8
  csv: ^6.0.0
  uuid: ^4.3.3
  convert: ^3.1.1
  geocoding: ^3.0.0
  fluttertoast: ^8.2.4
  flutter_map_marker_cluster: ^1.3.4
  lottie: ^3.0.0
  collection_providers: ^0.2.1
  flutter_map_animations: ^0.8.0
  just_audio: ^0.9.37
  native_qr: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  fake_async: ^1.3.0

  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter_launcher_icons:
  image_path: "assets/icon-blue-full.png"
  android: true
  ios: true

flutter:
  assets:
    - assets/icon.png
    - assets/icon-blue-full.png
    - assets/icon-128.png
    - assets/icon-round-1.png
    - assets/icon-round-2.png
    - assets/LD_logo_wordmark_blue.svg
    - assets/lottie/
    - assets/compass_needle.svg
    - assets/audio/silent.wav
    - assets/images/
  uses-material-design: true